version: '3'
services:
  mariadb:
    build: 
      context: ./docker/mariadb
      dockerfile: Dockerfile
    # networks:
    #   - my_network
    container_name: mariadb-container
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    expose:
      - "3306"

  dotnet-api:
    build:
      context: ./src
      dockerfile: Dockerfile
    # networks:
    #   - my_network
    links:
      - "mariadb:database"
    container_name: dotnet-core-container
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__MySQL=Server=database;User Id=root;Password=root;Database=db-boilerplate
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000 